"""Migrate

Revision ID: 974d856796e9
Revises: 5e83f6461466
Create Date: 2019-09-24 19:41:39.451314

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '974d856796e9'
down_revision = '5e83f6461466'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('pic', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'pic')
    # ### end Alembic commands ###
