"""Migrate

Revision ID: d813bcd49b42
Revises: 974d856796e9
Create Date: 2019-09-24 19:50:14.626727

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd813bcd49b42'
down_revision = '974d856796e9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vote', sa.Column('pich', sa.Integer(), nullable=True))
    op.add_column('vote', sa.Column('ward', sa.Integer(), nullable=True))
    op.drop_constraint('vote_pitch_fkey', 'vote', type_='foreignkey')
    op.drop_constraint('vote_word_fkey', 'vote', type_='foreignkey')
    op.create_foreign_key(None, 'vote', 'word', ['ward'], ['id'])
    op.create_foreign_key(None, 'vote', 'pitch', ['pich'], ['id'])
    op.drop_column('vote', 'pitch')
    op.drop_column('vote', 'word')
    op.add_column('word', sa.Column('pich', sa.Integer(), nullable=True))
    op.drop_constraint('word_pitch_fkey', 'word', type_='foreignkey')
    op.create_foreign_key(None, 'word', 'pitch', ['pich'], ['id'])
    op.drop_column('word', 'pitch')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('word', sa.Column('pitch', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'word', type_='foreignkey')
    op.create_foreign_key('word_pitch_fkey', 'word', 'pitch', ['pitch'], ['id'])
    op.drop_column('word', 'pich')
    op.add_column('vote', sa.Column('word', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('vote', sa.Column('pitch', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'vote', type_='foreignkey')
    op.drop_constraint(None, 'vote', type_='foreignkey')
    op.create_foreign_key('vote_word_fkey', 'vote', 'word', ['word'], ['id'])
    op.create_foreign_key('vote_pitch_fkey', 'vote', 'pitch', ['pitch'], ['id'])
    op.drop_column('vote', 'ward')
    op.drop_column('vote', 'pich')
    # ### end Alembic commands ###
